AWSTemplateFormatVersion: 2010-09-09
Description: StateMachine Creation
Parameters:
  Environment:
    Description: Select the Environment type as dev, qa or prod
    Type: String
    AllowedValues:
        - dev
        - qa
        - pro
  refLkhOrchFileNm:
    Description: Lakehouse Orch Framework Step Function File Name
    Type: String  
 
  refLkhOrchSMname:
    Description: Lakehouse Orch Framework Step Function File Name
    Type: String  
     
 
Resources:
  StepFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "nga-${Environment}-orch-step-functions-service-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: StepFunctionExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:

              # Allow invoking Lambda
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"

              # (Optional but recommended for debugging/logging)
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
                
    IngestionFrameworkState:            
      Type: AWS::StepFunctions::StateMachine
      Properties:
        DefinitionS3Location:
          Bucket: !Sub
            - 'klg-nga-${e}-kna-raw-intrnl-purva'
            - e: !Ref Environment
 
          Key: !Sub 'ingestion_framework/orchestration/statemachines/${refLkhOrchFileNm}'
        RoleArn: !GetAtt StepFunctionExecutionRole.Arn
        StateMachineName: !Sub
          - '${e}_orch_${n}'
          - e: !Ref Environment
            n: !Ref refLkhOrchSMname
        StateMachineType: STANDARD
       
Outputs:
 StateMachineOutPut:
    Description: State Machine Output
    Value: !Ref IngestionFrameworkState
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", IngestionFrameworkState ] ]