name: Deploy SQS + EventBridge Stack

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip all Lambda files
        run: | 
          cd scripts/lambda
            for file in *.py; do
              zip "${file%.py}.zip" "$file"
            done

      - name: Upload Lambda Zips
        run: |
          aws s3 sync scripts/lambda/ s3://${{ secrets.BUCKET_NAME }}/scripts/lambda/ --exclude "*.py" --size-only
      
      - name: Validate CloudFormation Template
        run: |
          aws cloudformation validate-template \
            --template-body file://infrastructure/etl-sqs-cfn.yml

      - name: Deploy CloudFormation Stack for SQS 
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/etl-sqs-cfn.yml \
            --stack-name sqs-for-ingestion \
            --parameter-overrides file://workflow_parameters/dev-sqs-parameters.json \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
         


      - name: Deploy Cloudformation Stack for Lambda
        run: |
          aws cloudformation create-stack \
            --stack-name lambda-for-ingestion \
            --template-body file://infrastructure/etl-lambda-cfn.yml \
            --parameters file://workflow_parameters/dev-lambda-parameters.json \
            --capabilities CAPABILITY_NAMED_IAM \
            --on-failure DELETE
